version: '3.9'
services:
  db:
    image: postgres
    container_name: rzheng-postgres
    # Volume mounted for database for the storage
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    # Environment variable are defined in .env file
    # .env should be git ignored
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


  # Back-end Spring Boot Application
  backend:
    image: eclipse-temurin:11
    command: ./gradlew bootRun
    volumes:
      - .:/usr/src/rzheng:rw
    working_dir: /usr/src/rzheng
    ports:
      - 8080:8080

    container_name: rzheng-spring-boot-dev
    depends_on:
      - db

    # Environment variables for Spring Boot Application.
    # These variables have to match in application.properties
    environment:
      - DB_SERVER=${DB_SERVER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


# Volumes for DB data
volumes:
  db-data: